# Generated by Django 3.2.12 on 2022-03-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('image', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('release_date', models.DateField()),
                ('lte_exists', models.TextField()),
                ('slug', models.TextField()),
            ],
        ),
    ]
