# Generated by Django 3.2.12 on 2022-04-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.TextField(),
        ),
    ]
